using System.Text;
using NvimManager.Core.Lua;
using NvimManager.Core.Models;

namespace NvimManager.Core.Services;

/// <summary>
/// Renders managed lazy.nvim configuration:
///   lua/nvimmanager/plugins.lua  – the plugin spec table
///   lua/nvimmanager.lua          – bootstrap + setup module (require("nvimmanager"))
///   init.lua                     – created only when absent or already managed
/// </summary>
public sealed class LazyConfigGenerator
{
    public const string ManagedMarker = "-- GENERATED BY NVIMMANAGER -- DO NOT EDIT MANUALLY.";

    private static readonly string[] SimpleKeys = { "priority", "lazy", "version", "branch", "dev", "dependencies", "event", "cmd", "ft", "keys", "build", "opts", "config", "init" };

    public string RenderPluginsFile(IEnumerable<LazySpec> specs)
    {
        var sb = new StringBuilder();
        sb.AppendLine(ManagedMarker);
        sb.AppendLine("-- Managed plugins for LazyVim-style setups. Generated by NvimManager.");
        sb.AppendLine("return {");
        foreach (var spec in specs.Where(s => s.Enabled).Select(RenderRawSpec))
        {
            foreach (var line in spec)
                sb.AppendLine(line);
            sb.AppendLine();
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private IEnumerable<string> RenderRawSpec(LazySpec spec)
    {
        yield return "  {";
        yield return $"    {(spec.Repo.Contains('/') ? LuaWriter.QuoteString(spec.Repo) : spec.Repo)},";

        if (spec.Priority.HasValue)
            yield return $"    priority = {spec.Priority.Value},";
        if (spec.Lazy.HasValue)
            yield return $"    lazy = {(spec.Lazy.Value ? "true" : "false")},";
        if (!string.IsNullOrWhiteSpace(spec.Version))
            yield return $"    version = {SmartRaw(spec.Version!)},";
        if (!string.IsNullOrWhiteSpace(spec.Branch))
            yield return $"    branch = {LuaWriter.QuoteString(spec.Branch!)},";
        if (spec.Dev)
            yield return "    dev = true,";

        if (spec.Dependencies.Count > 0)
            yield return $"    dependencies = {RenderStringArray(spec.Dependencies)},";

        string? events = RenderTrigger(spec.Events);
        if (events is not null) yield return $"    event = {events},";
        string? cmds = RenderTrigger(spec.Commands);
        if (cmds is not null) yield return $"    cmd = {cmds},";
        string? fts = RenderTrigger(spec.FileTypes);
        if (fts is not null) yield return $"    ft = {fts},";

        if (!string.IsNullOrWhiteSpace(spec.Keys))
            yield return $"    keys = {SmartRaw(spec.Keys!)},";
        if (!string.IsNullOrWhiteSpace(spec.Build))
            yield return $"    build = {SmartRaw(spec.Build!)},";

        if (spec.Opts is LuaTable optsTable)
        {
            string optsText = LuaWriter.Serialize(optsTable);
            yield return $"    opts = {optsText},";
        }
        else if (spec.Opts is RawLua rawOpts && !string.IsNullOrWhiteSpace(rawOpts.Code))
        {
            string optsText = rawOpts.Code.Trim();
            yield return $"    opts = {optsText},";
        }

        if (!string.IsNullOrWhiteSpace(spec.Config))
        {
            yield return "    config = function(_, opts)";
            foreach (var line in spec.Config!.TrimEnd().Split('\n'))
                yield return $"      {line.TrimEnd()}";
            yield return "    end,";
        }

        if (!string.IsNullOrWhiteSpace(spec.Init))
        {
            yield return "    init = function()";
            foreach (var line in spec.Init!.TrimEnd().Split('\n'))
                yield return $"      {line.TrimEnd()}";
            yield return "    end,";
        }

        yield return "  },";
    }

    private static string? RenderTrigger(IReadOnlyList<string> values)
    {
        if (values is null || values.Count == 0) return null;
        return values.Count == 1 ? LuaWriter.QuoteString(values[0]) : RenderStringArray(values);
    }

    private static string RenderStringArray(IReadOnlyList<string> values)
    {
        var sb = new StringBuilder("{ ");
        for (int i = 0; i < values.Count; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(LuaWriter.QuoteString(values[i]));
        }
        sb.Append(" }");
        return sb.ToString();
    }

    /// <summary>
    /// Renders one plugin as a standalone AstroNvim-style spec file
    /// (lua/plugins/&lt;name&gt;.lua). Same lazy.nvim table syntax as the
    /// managed bundle, so schema opts and lazy options carry over as-is.
    /// </summary>
    public string RenderAstroSpecFile(LazySpec spec)
    {
        var sb = new StringBuilder();
        sb.AppendLine(ManagedMarker);
        sb.AppendLine($"-- Managed by NvimManager for AstroNvim ({spec.Repo}). Safe to delete; it is regenerated on save.");
        sb.AppendLine("return {");
        foreach (var line in RenderRawSpec(spec))
            sb.AppendLine(line);
        sb.AppendLine("}");
        return sb.ToString();
    }

    public string RenderModule()
    {
        var sb = new StringBuilder();
        sb.AppendLine(ManagedMarker);
        sb.AppendLine("-- Bootstrap lazy.nvim, then load the plugin specs managed by NvimManager.");
        sb.AppendLine("local lazypath = vim.fn.stdpath(\"data\") .. \"/lazy/lazy.nvim\"");
        sb.AppendLine("local uv = vim.uv or vim.loop");
        sb.AppendLine("if not uv.fs_stat(lazypath) then");
        sb.AppendLine("  vim.fn.system({");
        sb.AppendLine("    \"git\", \"clone\", \"--filter=blob:none\",");
        sb.AppendLine("    \"https://github.com/folke/lazy.nvim.git\",");
        sb.AppendLine("    \"--branch=stable\",");
        sb.AppendLine("    lazypath,");
        sb.AppendLine("  })");
        sb.AppendLine("end");
        sb.AppendLine("vim.opt.rtp:prepend(lazypath)");
        sb.AppendLine();
        sb.AppendLine("require(\"lazy\").setup(require(\"nvimmanager.plugins\"), {");
        sb.AppendLine("  install = { colorscheme = { \"habamax\" } },");
        sb.AppendLine("})");
        return sb.ToString();
    }

    public string RenderInitLua()
    {
        return ManagedMarker + "\n\n-- NvimManager-managed configuration. Start the managed plugin setup:\nrequire(\"nvimmanager\")\n";
    }

    /// <summary>
    /// Writes the managed config files. Never overwrites a user init.lua that is
    /// not already managed; instead returns a message telling them to opt in.
    /// </summary>
    public IReadOnlyList<string> ApplyToDisk(NvimPaths paths, IReadOnlyList<LazySpec> specs)
    {
        var messages = new List<string>();

        string pluginsPath = paths.PluginsLuaPath;
        Directory.CreateDirectory(Path.GetDirectoryName(pluginsPath)!);
        File.WriteAllText(pluginsPath, RenderPluginsFile(specs));
        messages.Add($"Wrote {pluginsPath}");

        string modulePath = paths.ModulePath;
        Directory.CreateDirectory(Path.GetDirectoryName(modulePath)!);
        File.WriteAllText(modulePath, RenderModule());
        messages.Add($"Wrote {modulePath}");

        if (File.Exists(paths.InitLuaPath))
        {
            string current = File.ReadAllText(paths.InitLuaPath);
            if (current.Contains(ManagedMarker))
            {
                File.WriteAllText(paths.InitLuaPath, RenderInitLua());
                messages.Add($"Updated {paths.InitLuaPath}");
            }
            else
            {
                messages.Add($"Kept existing {paths.InitLuaPath}: add 'require(\"nvimmanager\")' to it to enable the managed config.");
            }
        }
        else
        {
            Directory.CreateDirectory(paths.ConfigDir);
            File.WriteAllText(paths.InitLuaPath, RenderInitLua());
            messages.Add($"Created {paths.InitLuaPath}");
        }

        return messages;
    }

    private static object SmartRaw(string value)
    {
        string trimmed = value.Trim();
        if (LooksLikeLua(trimmed))
            return new RawLua(trimmed);
        return LuaWriter.QuoteString(trimmed);
    }

    private static bool LooksLikeLua(string value)
        => value.Contains('(') || value.Contains('=') || value.Contains('\n')
           || value.StartsWith('{') || value.StartsWith('[');
}